name: module3_task2
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
jobs:
  module3_task2:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task2/setup.sh
      - run: cd module3_task2 && make lint
      - run: cd module3_task2 && make build
      - run: cd module3_task2 && make package
      - run: cd module3_task2 && make unit-tests
      - run: cd module3_task2 && make integration-tests
      - run: cd module3_task2 && make validate
      - uses: actions/upload-artifact@v3
        with:
          path: module3_task2/awesome-website.zip