name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
jobs:
  task0:
    runs-on: ubuntu-latest # It will run on an "ubuntu-latest" virtual machine provided by GitHub.
    steps:
      - uses: actions/checkout@v3 # allows you to get the source code from the repository
      - run: cd module3_task0 && make help
