name: release_drafter
on:
  push:
    branches:
      - main
    tags: "1.0.1"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
jobs:
  update_release_draft:
    permissions: write-all
    name: release_drafter_job
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "changelog"
          output: changelog.md
