name: release_drafter
on:
  push:
    branches:
      - main
    tags: "1.0.1"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}